name: CI Next.js

on:
  push:
    branches:
      - main
      - develop
      - staging
  pull_request:
    branches:
      - main
      - develop
      - staging

jobs:
  build_dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Run tests
        run: |
          cd frontend
          npm run test

      - name: Build for Development
        run: |
          cd frontend
          cp .env.development .env
          npm run build

      - name: Deploy to Vercel (Dev)
        run: |
          cd frontend
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --env NODE_ENV=development

  build_staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Run tests
        run: |
          cd frontend
          npm run test

      - name: Build for Staging
        run: |
          cd frontend
          cp .env.staging .env
          npm run build

      - name: Deploy to Vercel (Staging)
        run: |
          cd frontend
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --env NODE_ENV=staging

  build_prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Run tests
        run: |
          cd frontend
          npm run test

      - name: Build for Production
        run: |
          cd frontend
          cp .env.production .env
          npm run build

      - name: Deploy to Vercel (Production)
        run: |
          cd frontend
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --env NODE_ENV=production
